controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_index:
    path: /
    controller: 'App\Controller\DefaultController::bbq'